name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job de pruebas
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  # Job para construir la imagen Docker
  build:
    runs-on: ubuntu-latest
    needs: test  # El job de construcción depende de que las pruebas hayan pasado

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t daysibv05/myimage:latest .

  # Job para escanear vulnerabilidades en la imagen Docker
  scan:
    runs-on: ubuntu-latest
    needs: build  # El job de escaneo depende de que la imagen haya sido construida

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Trivy for vulnerability scanning
        uses: aquasecurity/trivy-action@v0.8.0

        with:
          image-ref: your-docker-image-name:latest # Reemplaza esto con tu nombre de imagen Docker

      - name: Run Trivy scan
        run: |
          docker pull your-docker-image-name:latest  # Asegúrate de usar el nombre de tu imagen
          trivy image --no-progress your-docker-image-name:latest
          
      - name: Upload Trivy scan results
        uses: actions/upload-artifact@v3
        with:
          name: trivy-scan-report
          path: trivy-report.json

  # Job de despliegue
  deploy:
    runs-on: ubuntu-latest
    needs: scan  # El job de despliegue depende de que el escaneo haya sido exitoso

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: daysibv05
          password: RJpE4qSxMwGEe2_

      - name: Deploy to Docker
        run: |
          docker run -d your-docker-image-name:latest
