name: CI/CD Pipeline

on:
  push:
    branches:
      - master   # Usamos la rama 'master' como principal
  pull_request:
    branches:
      - master   # También para pull requests hacia 'master'

jobs:
  # Job de pruebas
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Ajustado a la versión Node.js que estás usando

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  # Job para construir la imagen Docker
  build:
    runs-on: ubuntu-latest
    needs: test  # El job de construcción depende de que las pruebas hayan pasado

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t daysibv05/myapp:latest .

      # Agregar la construcción de la imagen con el Dockerfile en el directorio .github/workflows
      - name: Build Docker image with specific Dockerfile
        run: |
          docker build -t daysibv05/infosec-chat:latest -f .github/workflows/Dockerfile .

  # Job para escanear vulnerabilidades en la imagen Docker
  scan:
    runs-on: ubuntu-latest
    needs: build  # El job de escaneo depende de que la imagen haya sido construida

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run Trivy scan
        run: |
          docker pull daysibv05/infosec-chat:latest
          trivy image --no-progress daysibv05/infosec-chat:latest

      - name: Upload Trivy scan results
        uses: actions/upload-artifact@v3
        with:
          name: trivy-scan-report
          path: trivy-report.json

  # Job de despliegue
  deploy:
    runs-on: ubuntu-latest
    needs: scan  # El job de despliegue depende de que el escaneo haya sido exitoso

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: daysibv05
          password: RJpE4qSxMwGEe2_

      - name: Deploy to Docker
        run: |
          docker run -d daysibv05/infosec-chat:latest


