name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job de pruebas
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  # Job para escanear vulnerabilidades en la imagen Docker
  scan:
    runs-on: ubuntu-latest
    needs: test  # El job de escaneo depende de que las pruebas hayan pasado

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/your-docker-image-name:latest .

      - name: Set up Trivy for vulnerability scanning
        uses: aquasecurity/trivy-action@v0.8.0
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/your-docker-image-name:latest

      - name: Run Trivy scan
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/your-docker-image-name:latest
          trivy image --no-progress ${{ secrets.DOCKER_USERNAME }}/your-docker-image-name:latest
          
      - name: Upload Trivy scan results
        uses: actions/upload-artifact@v3
        with:
          name: trivy-scan-report
          path: trivy-report.json

  # Job de despliegue
  deploy:
    runs-on: ubuntu-latest
    needs: scan  # El job de despliegue depende de que el escaneo haya sido exitoso

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: daysibv05
          password: RJpE4qSxMwGEe2_

      - name: Deploy to Docker
        run: |
          docker run -d ${{ secrets.DOCKER_USERNAME }}/your-docker-image-name:latest
